openapi: 3.0.3
info:
  title: Device Service API
  version: 1.0.0
  description: API for managing devices

servers:
  - url: /api

paths:
  /devices:
    get:
      summary: Get devices
      tags: [Device]
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: size
          in: query
          schema: { type: integer, default: 10 }
        - name: search
          in: query
          schema: { type: string }
        - name: sort
          in: query
          schema: { type: string }
        - name: order
          in: query
          schema: { type: string }
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/DeviceStatus"
      responses:
        "200":
          description: Device list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedDeviceResponse"

    post:
      summary: Create device
      tags: [Device]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceCreateRequest"
      responses:
        "201":
          description: Device created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceCreateResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

  /devices/{deviceId}:
    get:
      summary: Get device detail
      tags: [Device]
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Device detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceGetResponse"
        "404":
          $ref: "#/components/responses/NotFound"

    patch:
      summary: Update device
      tags: [Device]
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceUpdateRequest"
      responses:
        "200":
          description: Device updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceUpdateResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"

    delete:
      summary: Delete device
      tags: [Device]
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Device deleted
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"

components:
  schemas:
    DeviceStatus:
      type: string
      enum: [ ACTIVE, INACTIVE, OFFLINE ]

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
        detail:
          type: string
        path:
          type: string
        code:
          type: string
        timestamp:
          type: string
          format: date-time

    PagedDeviceResponse:
      type: object
      properties:
        count_data:
          type: number
        page:
          type: number
        size:
          type: number
        total_pages:
          type: number
        devices:
          type: array
          items:
            $ref: "#/components/schemas/DeviceGetResponse"

    DeviceCreateRequest:
      type: object
      required: [device_name, device_type, cluster_id]
      properties:
        device_name:
          type: string
        device_type:
          type: string
        cluster_id:
          type: string

    DeviceCreateResponse:
      type: object
      properties:
        deviceId:
          type: string
        deviceName:
          type: string
        deviceType:
          type: string
        clusterId:
          type: string
        status:
          $ref: "#/components/schemas/DeviceStatus"
        createdAt:
          type: string
          format: date-time

    DeviceGetResponse:
      type: object
      properties:
        deviceId:
          type: string
        deviceName:
          type: string
        deviceType:
          type: string
        clusterId:
          type: string
        status:
          $ref: "#/components/schemas/DeviceStatus"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    DeviceUpdateRequest:
      type: object
      properties:
        device_name:
          type: string
        device_type:
          type: string
        status:
          $ref: "#/components/schemas/DeviceStatus"

    DeviceUpdateResponse:
      type: object
      properties:
        deviceId:
          type: string
        deviceName:
          type: string
        deviceType:
          type: string
        status:
          $ref: "#/components/schemas/DeviceStatus"
        clusterId:
          type: string
        updatedAt:
          type: string
          format: date-time

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
